export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_SERVER_TOKEN = 'SET_SERVER_TOKEN';
export const SET_USER_LOGGING_FLAG = 'SET_USER_LOGGING_FLAG';
export const SET_ERROR_INFO = 'SET_ERROR_INFO';
